### ISSUE TITLE
Like and Dislike Buttons should be changed

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/Interactive-Book#75] opened 2019-11-14 11:51 UTC
Like and dislike buttons hover when clicked and the like button requires padding as it forms an incomplete square.
![like](https://user-images.githubusercontent.com/42520146/68854941-2d07be80-0703-11ea-8ff9-f4ca9fc8ba55.PNG)

**Comment by satu0king** [comment] 2019-11-28 04:18
We are using Disqus for comments, I don't think we can change it. Moreover, this has to be done from the admin side. On the other side there are some jekyll only comment systems. Could you checkout StaticMan and let us know if its a good idea? 
@sakshi1499

**Comment by sakshi1499** [comment] 2019-11-28 04:41
@satu0king okay sure, will look into it.

**Comment by sakshi1499** [comment] 2019-11-28 04:57
@satu0king I read the whole thing. There are many disadvantages of Disqus. Some of them being:

- It stores all the comments people are making, and gives us no control over it.

- It has no track record on privacy, so its not really safe.

- Its not really flexible in customization and comments section might clash.

Staticman is a good solution to all these problems. Though, I feel that this issue would be too hard for GCI participants. I think with some help, I can work on this. What do you suggest?

**Comment by aayush-05** [comment] 2020-02-14 16:09
@satu0king I checked with Staticman, it's good but the problem is it pushes data on every comment made on the website as a commit on Github. Won't it mess up the whole commit history of the repo ?

**Comment by aayush-05** [comment] 2020-05-13 06:52
@tachyons @nitin10s can we close this one, no access to disqus internal files

**Closed** 2020-05-13 07:31 UTC
