### ISSUE TITLE
Non-clickabe links of the references page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#38] opened 2019-11-05 20:26 UTC
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
For now to visit a link user need to copy the link and open it in a new browser. Make all the links of references page clickable so as it should open in a new window.

**Comment by dev9414** [comment] 2019-11-07 17:37
Already opened at #36

**Comment by tachyons** [comment] 2019-11-13 08:31
Duplicate of #37

**Closed** 2019-11-27 11:51 UTC
